### ISSUE TITLE
[BUG] Kraken API Rate Limit Exceeded error when there are multiple hanging orders.

### ISSUE THREAD

**Issue by ZeroCool940711** [CoinAlpha/hummingbot#2380]
**Describe the bug**
Seems like HummingBot is sending too many requests in a short period of time when placing orders or getting the order status, mostly when there are a lot of orders hanging, when this happens it fails to get the order status from kraken, because it's hitting the API rate limit as its sending too many requests at the same time, this causes the bot to have a wrong balance which can be negative or too far away from the real amount the account could have because it will add or reduce to the balance the currency it thinks are been used on open orders, bellow is a screenshot showing the bot running where this happened.

To avoid this and make sure HummingBot can get the order status correctly and not hit the api rate limit it needs to be aware of the maximum number of requests an exchange allows and merge multiple requests into a single one. Kraken has multiple request limits depending on the type of requests that is been made and it also has a limit on the number of requests you can send in a certain amount of time, the general information for the rest api can be found on [this link](https://www.kraken.com/en-us/features/api), specific information about the [REST API can be found here](https://support.kraken.com/hc/en-us/articles/360022635612-Request-Limits-REST-API-), Kraken also has a [Batch Order endpoint](https://support.kraken.com/hc/en-us/articles/360022853511-Batch-Order) on their api, HummingBot should collect the requests it will be making when `order_refresh_time` or other options trigger, and if multiple orders are hanging and it needs to get the status or multiple orders will be placed/edited because we are using multiple order levels then it should use the [Batch Order](https://support.kraken.com/hc/en-us/articles/360022853511-Batch-Order) endpoint instead of sending individual requests which would result in it hitting the api rate limit, another thing to have in mind is that orders been filled also count toward the api request limit which for the REST API is around 500 calls every 10 seconds, [here ](https://support.kraken.com/hc/en-us/articles/206548367-What-are-the-API-rate-limits-)is another useful article from Kraken.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/5977640/94222384-11804f00-fea2-11ea-91f5-57e104f0dfd4.png)

**Release version**
Version: dev-0.32.0 (latest commit from branch `development` `09/24/2020: 08:27PM MST` )

**Attachments**
Config File:  [conf_pure_mm_kraken_DOT_USD_2.zip](https://github.com/CoinAlpha/hummingbot/files/5280408/conf_pure_mm_kraken_DOT_USD_2.zip)
Strategy Log File: [logs_conf_pure_mm_kraken_dot_usd_2.zip](https://github.com/CoinAlpha/hummingbot/files/5280410/logs_conf_pure_mm_kraken_dot_usd_2.zip)

HummingBot Log file: [logs_hummingbot.zip](https://github.com/CoinAlpha/hummingbot/files/5280409/logs_hummingbot.zip)

**Discord Username: Tukirito**

**Comment by ZeroCool940711** [comment]
More information on this issue, for what I saw the max number of hanging orders the bot can handle for kraken is 6, as soon as you have 6 hanging orders if it tries to put another more order or get the information for those orders the bot starts to get api rate limit error, my guess is that it tries to get the order status using multiple requests to the API, also seems like when this happens the bot completely ignores the `order_refresh_time` value and startst to send even more requests than when its running normally, in my case I have set the `order_refresh_time` to 60 seconds, when the bot runs normally and before hitting the api rate limit it make the requests at exactly 60 seconds but after it hits the api rate limit it starts to make a lot of requests every 10 seconds, this results in the API getting temporarily banned after sometimes, usually for 15 minutes or a couple of hours. Here is a screenshot showing the error happening again as soon as HB reached 6 hanging orders and if you see the logs you will see that it starts to make requests every 10 seconds as I said before.

![image](https://user-images.githubusercontent.com/5977640/94250482-21198b00-fed6-11ea-8491-1ca07af39a8d.png)

Config file: [conf_pure_mm_kraken_DOT_USD_2.zip](https://github.com/CoinAlpha/hummingbot/files/5281844/conf_pure_mm_kraken_DOT_USD_2.zip)
Strategy Log File: [logs_conf_pure_mm_kraken_dot_usd_2.zip](https://github.com/CoinAlpha/hummingbot/files/5281824/logs_conf_pure_mm_kraken_dot_usd_2.zip)
 
HummingBot Log File: [logs_hummingbot.zip](https://github.com/CoinAlpha/hummingbot/files/5281848/logs_hummingbot.zip)

**Comment by tomma100** [comment]
this does not appear fixed in 0.34 - as soon as too many hanging orders end up on the book it triggers the rate limit

i do not see how the pause/resume command can help in automated trading - it seems like every 10 seconds an api request is made per hanging order

would it not make more sense to do a single api request and fetch all open orders in one go?

also i think kraken has a private websocket - https://support.kraken.com/hc/en-us/articles/360022839851-Open-orders could that be employed?

**Comment by keithbaum** [comment]
This error is related to bug fix from #2204. After fix is pushed this issue should be fixed.

**Comment by keithbaum** [comment]
@tomma100 and @ZeroCool940711, could you please tell me if you are still experiencing the same errors. Last week I pushed a fix that should address this issue. You can find it from latest development branch

**Comment by ZeroCool940711** [comment]
@keithbaum I'm no longer using Kraken, I started using Binance.US when the connector was added for it, all my funds are on Binance.US right now so it would be hard for me to test if its still throwing errors there, I might try to add some funds another day to test it but you will probably have better luck and better feedback if its from someone that is currently using Kraken.

**Comment by tomma100** [comment]
sorry i missed your request - i what version of hummingbot do i need to run - i can test this over the weekend no problem

**Comment by RC-13** [comment]
@tomma100 sorry for the late response, the fix has been merge to the development branch- v0.36.0 and will be available soon to the latest branch. Tentative release date, anytime within the day (Feb 8 PST). An announcement will be sent through discord and a newsletter will be sent if 0.36.0 is released.
