### ISSUE TITLE
Failed Test PR #315 - Failed to fetch trade updates

### ISSUE THREAD

**Issue by mrhzysbl** [CoinAlpha/hummingbot#317]
## Summary and Screenshots
After starting the PMM strategy in the client, 2 errors was thrown in a loop. No orders were created on the client/exchange

https://user-images.githubusercontent.com/120451804/224633329-8eacc40a-82b4-423d-b679-e6d07c40076f.mov

<img width="920" alt="Screen Shot 2023-03-13 at 3 22 44 PM" src="https://user-images.githubusercontent.com/120451804/224633801-dff16f1c-b0ed-478e-9372-5303da516729.png">

```ruby
2023-03-13 14:33:10,043 - 16244 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/network/poll failed. See logs for more details.
```

```ruby
2023-03-13 15:01:20,014 - 16244 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - WARNING - Failed to fetch trade updates for order 0x00000000000000000020c9049fe455a22056ec825d5a5c5cf3f5cabec7f21742. Error: Error on POST https://localhost:15888/network/poll Error: {'message': 'The request is missing the key: txHash', 'httpErrorCode': 404, 'errorCode': -1, 'stack': 'Error: The request is missing the key: txHash\n    at throwIfErrorsExist (/Users/admin/gateway-dex/dist/src/services/validators.js:38:15)\n    at /Users/admin/gateway-dex/dist/src/services/validators.js:103:40\n    at /Users/admin/gateway-dex/dist/src/network/network.routes.js:68:41\n    at Generator.next (<anonymous>)\n    at /Users/admin/gateway-dex/dist/src/network/network.routes.js:31:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/admin/gateway-dex/dist/src/network/network.routes.js:27:12)\n    at /Users/admin/gateway-dex/dist/src/network/network.routes.js:67:88\n    at /Users/admin/gateway-dex/dist/src/services/error-handler.js:37:28\n    at Layer.handle [as handle_request] (/Users/admin/gateway-dex/node_modules/express/lib/router/layer.js:95:5)'}
Traceback (most recent call last):
  File "/Users/admin/dexalot-updated/hummingbot/connector/exchange_py_base.py", line 975, in _update_orders_fills
    trade_updates = await self._all_trade_updates_for_order(order=order)
  File "/Users/admin/dexalot-updated/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 584, in _all_trade_updates_for_order
    trade_updates = await self._api_data_source.get_all_order_fills(in_flight_order=order)
  File "/Users/admin/dexalot-updated/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 180, in get_all_order_fills
    await self.get_order_status_update(in_flight_order=in_flight_order)
  File "/Users/admin/dexalot-updated/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 168, in get_order_status_update
    status_update = await self._get_order_status_update_from_transaction_status(in_flight_order=in_flight_order)
  File "/Users/admin/dexalot-updated/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 344, in _get_order_status_update_from_transaction_status
    transaction_data = await self._get_gateway_instance().get_transaction_status(
  File "/Users/admin/dexalot-updated/hummingbot/core/gateway/gateway_http_client.py", line 415, in get_transaction_status
    return await self.api_request("post", f"{network_path}/poll", request, fail_silently=fail_silently)
  File "/Users/admin/dexalot-updated/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/Users/admin/dexalot-updated/hummingbot/core/gateway/gateway_http_client.py", line 206, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:15888/network/poll Error: {'message': 'The request is missing the key: txHash', 'httpErrorCode': 404, 'errorCode': -1, 'stack': 'Error: The request is missing the key: txHash\n    at throwIfErrorsExist (/Users/admin/gateway-dex/dist/src/services/validators.js:38:15)\n    at /Users/admin/gateway-dex/dist/src/services/validators.js:103:40\n    at /Users/admin/gateway-dex/dist/src/network/network.routes.js:68:41\n    at Generator.next (<anonymous>)\n    at /Users/admin/gateway-dex/dist/src/network/network.routes.js:31:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/admin/gateway-dex/dist/src/network/network.routes.js:27:12)\n    at /Users/admin/gateway-dex/dist/src/network/network.routes.js:67:88\n    at /Users/admin/gateway-dex/dist/src/services/error-handler.js:37:28\n    at Layer.handle [as handle_request] (/Users/admin/gateway-dex/node_modules/express/lib/router/layer.js:95:5)'}
```

## Steps To Reproduce

1. Clone and install branch
2. Setup and run gateway using the feature PR for Dexalot
3. Connect Dexalot wallet
4. Create and run a pure MM strategy using Dexalot

## Attachments

[Dexalot_issue.zip](https://github.com/CoinAlpha/hummingbot/files/10954567/Dexalot_issue.zip)

**Comment by petioptrv** [comment]
This should be resolved now

**Comment by rxlxrxsx** [comment]
Tested on commit [0f46fb7](https://github.com/CoinAlpha/hummingbot/pull/315/commits/0f46fb7af6efa7577716c87042542291e9232d8a) confirmed orders are now being created however were still encountering errors related to fetching trade updates:

<img width="1422" alt="Screen Shot 2023-03-14 at 12 04 47 PM" src="https://user-images.githubusercontent.com/64377055/225097453-6a4925b4-cdb9-4d1e-88c4-60fa7b7ce454.png">

```python
2023-03-14 12:04:35,961 - 6144 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - WARNING - Failed to fetch trade updates for order 0x00000000000000000018938001cbe71cb9cfe27e999a2157f2795171ecb9615f. Error: Error executing request GET https://api.dexalot.com/privapi/signed/orders/0x0000000000000000000000000000000000000000000000000000000063d938c9. HTTP status is 404. Error: {"message":""}
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/exchange_py_base.py", line 976, in _update_orders_fills
    trade_updates = await self._all_trade_updates_for_order(order=order)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 590, in _all_trade_updates_for_order
    trade_updates = await self._api_data_source.get_all_order_fills(in_flight_order=order)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 181, in get_all_order_fills
    await self.get_order_status_update(in_flight_order=in_flight_order)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 172, in get_order_status_update
    status_update = await self._get_order_status_update_with_order_id(in_flight_order=in_flight_order)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 399, in _get_order_status_update_with_order_id
    resp = await self._api_get(
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 473, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 499, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.dexalot.com/privapi/signed/orders/0x0000000000000000000000000000000000000000000000000000000063d938c9. HTTP status is 404. Error: {"message":""}
```

```python
2023-03-14 12:04:37,060 - 6144 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error executing request GET https://api.dexalot.com/privapi/signed/orders/0x0000000000000000000000000000000000000000000000000000000063d938c8. HTTP status is 404. Error: {"message":""}
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/gateway_clob_api_data_source_base.py", line 483, in _wait_for_transaction_to_be_included_in_a_block_and_request_order_status_update
    await self.get_order_status_update(in_flight_order=in_flight_order)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 172, in get_order_status_update
    status_update = await self._get_order_status_update_with_order_id(in_flight_order=in_flight_order)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 399, in _get_order_status_update_with_order_id
    resp = await self._api_get(
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 473, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 499, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.dexalot.com/privapi/signed/orders/0x0000000000000000000000000000000000000000000000000000000063d938c8. HTTP status is 404. Error: {"message":""}
```

Logs and config: [dexalot_failed_to_fetch.zip](https://github.com/CoinAlpha/hummingbot/files/10972259/dexalot_failed_to_fetch.zip)

**Comment by petioptrv** [comment]
@rxlxrxsx, the error here is different from the original error. The error you're observing for orders not found, which is normal to have with Dexalot due to the time it takes between order request, blockchain inclusion, and Dexalot server update. The key is to make sure that the orders are eventually found by hummingbot, that all trade fills are recorded, and that no orders are left as orphans on the exchange once the bot stops.

I pushed a [change](https://github.com/CoinAlpha/hummingbot/pull/315/commits/a7766ee362a2bf49b16a6acf4ce5bea28c7b8a5f) to make this particular error message clearer. It should now say that the order was not found.

**Comment by rxlxrxsx** [comment]
Tested using commit [cf2023c](https://github.com/CoinAlpha/hummingbot/pull/315/commits/cf2023cb9ab91fb7404f4b9ce8b01210f9f94763) and confirmed I'm now seeing the changes.
