### ISSUE TITLE
Failed Test PR #315 - Failed to fetch trade updates when restarting a strategy using Injective

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#319]
## Summary and Screenshots
Getting this error when restarting a strategy using Injective.

<img width="1422" alt="Screen Shot 2023-03-13 at 11 08 55 AM" src="https://user-images.githubusercontent.com/64377055/224801390-2b809b03-e888-4f8b-97a4-a0a19bc00077.png">

```python
2023-03-13 11:08:24,058 - 12105 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - WARNING - Failed to fetch trade updates for order BIJUT5f6cb240a8068d6e3f2509794b922eaf289e249424ddd. Error: cannot convert float NaN to integer
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/exchange_py_base.py", line 975, in _update_orders_fills
    trade_updates = await self._all_trade_updates_for_order(order=order)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 590, in _all_trade_updates_for_order
    trade_updates = await self._api_data_source.get_all_order_fills(in_flight_order=order)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 449, in get_all_order_fills
    updated_at=int(in_flight_order.last_update_timestamp * 1e3)
ValueError: cannot convert float NaN to integer
2023-03-13 11:08:24,068 - 12105 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - WARNING - Failed to fetch trade updates for order SIJUT5f6cb240a90b1d6e3f2509794b922eaf289e249424ddd. Error: cannot convert float NaN to integer
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/exchange_py_base.py", line 975, in _update_orders_fills
    trade_updates = await self._all_trade_updates_for_order(order=order)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 590, in _all_trade_updates_for_order
    trade_updates = await self._api_data_source.get_all_order_fills(in_flight_order=order)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 449, in get_all_order_fills
    updated_at=int(in_flight_order.last_update_timestamp * 1e3)
ValueError: cannot convert float NaN to integer
```

## Steps To Reproduce
1. Clone and install branch
2. Setup and run gateway using the feature PR for Dexalot
3. Connect Injective wallet
4. Create and run a pure MM strategy using Injective
5. Run for a couple minutes or let the bot create and cancel orders then restart the strategy

## Test Result Comparison
I tried replicating this on the foundation repository however I encountered an [issue](https://github.com/hummingbot/hummingbot/issues/6143) which further blocks testing.

## Attachments
Logs and config: 
[inective_315.zip](https://github.com/CoinAlpha/hummingbot/files/10960771/inective_315.zip)

**Comment by petioptrv** [comment]
This is an existing issue. I have addressed it on the Injective batch orders PR and merged the changes into this PR. This should be fixed now.

**Comment by rxlxrxsx** [comment]
Still getting this issue on the latest commit [0f46fb7](https://github.com/CoinAlpha/hummingbot/pull/315/commits/0f46fb7af6efa7577716c87042542291e9232d8a) using the steps provided above.

<img width="1423" alt="Screen Shot 2023-03-14 at 9 42 25 AM" src="https://user-images.githubusercontent.com/64377055/225072635-dbddd82e-828f-494a-aa58-b78c937d5156.png">


```python
2023-03-14 09:41:41,039 - 3973 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - WARNING - Failed to fetch trade updates for order BIJUT5f6de0e61a94de6bad9b4bb8f5c241eee85bfb0f87040. Error: cannot convert float NaN to integer
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/exchange_py_base.py", line 976, in _update_orders_fills
    trade_updates = await self._all_trade_updates_for_order(order=order)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 590, in _all_trade_updates_for_order
    trade_updates = await self._api_data_source.get_all_order_fills(in_flight_order=order)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 449, in get_all_order_fills
    updated_at=int(in_flight_order.last_update_timestamp * 1e3)
ValueError: cannot convert float NaN to integer
```

Logs and config:
[injective.zip](https://github.com/CoinAlpha/hummingbot/files/10971067/injective.zip)

**Comment by petioptrv** [comment]
This should be now fixed with the merger of the upstream injective changes: [4e5f70e](https://github.com/CoinAlpha/hummingbot/pull/315/commits/4e5f70e32215adf08c990ea2b5db2eb55c15f459)

**Comment by rxlxrxsx** [comment]
Tested on commit [cf2023c](https://github.com/CoinAlpha/hummingbot/pull/315/commits/cf2023cb9ab91fb7404f4b9ce8b01210f9f94763) and confirmed fixed.
