### ISSUE TITLE
[BUG] hummingbot.core.utils.kill_switch - ERROR - Error calculating profitability

### ISSUE THREAD

**Issue by gonchs** [CoinAlpha/hummingbot#557]
**Describe the bug**
```
2019-07-16 18:18:06,329 - hummingbot.core.utils.kill_switch - ERROR - Error calculating profitability: 'USDC'
Traceback (most recent call last):
  File "/hummingbot/core/utils/kill_switch.py", line 34, in check_profitability_loop
    self._profitability = self._hummingbot_application.calculate_profitability() / 1e2
  File "/hummingbot/client/command/history_command.py", line 113, in calculate_profitability
    performance_analysis: PerformanceAnalysis = self.get_performance_analysis_with_updated_balance()
  File "/hummingbot/client/command/history_command.py", line 64, in get_performance_analysis_with_updated_balance
    amount = self.starting_balances[asset_name][market_name] if is_starting \
KeyError: 'USDC'
```

**Screenshot**

https://cl.ly/79f939304013

**Steps To Reproduce**
1. Install the bot on OSX
2. Use [these configs](https://gist.github.com/gonchs/de774faece8a56db217de1b2760cb614)
3. Run the bot

**Release version**
0.10.0

Bug bounty ETH address: 0xD0d44C9e51244eBfd70187548255d8e844567a92

**Comment by mifeng** [comment]
This is because we had to remove one of our data feed providers (CoinMetrics) in the latest release. Our current data feed provider doesn't have USDC prices.

We'll issue a more permanent fix for Data Feeds in the 0.11.0 release, which will be in approx 2 weeks.

**Comment by gonchs** [comment]
This appears to have been fixed in https://github.com/CoinAlpha/hummingbot/commit/6428be630c2e4eb8f6ab4c66f058403d7a940d45 (merged to master).

**Comment by hongson1981** [comment]
This issue still occur in version 0.11.1, please check log
[hummingbot_logs_2019-07-31-13-26-16.log](https://github.com/CoinAlpha/hummingbot/files/3452111/hummingbot_logs_2019-07-31-13-26-16.log)
